// Generated by kei_emit from async_greeter_hello.kei.
// Do not edit; regenerate with `kei build`.

import * as asyncGreeter from "async-greeter";

/**
 * uses Async
 */
export async function helloAsync(name: string): Promise<string> {
  return await asyncGreeter.greetAsync(name);
}
//# sourceMappingURL=async_greeter_hello.ts.map
