// Generated by kei_emit from async_greet.kei.
// Do not edit; regenerate with `kei build`.

import { KeiContractViolation } from "@kei/runtime";

/**
 * uses Async
 * ensures result == "user"
 */
export async function fetchName(id: number): Promise<string> {
  const kei$result = await (async (): Promise<string> => {
    return "nobody";
  })();
  if (!(kei$result === "user")) {
    throw new KeiContractViolation({
      clause: "ensures",
      func: "fetchName",
      condition: "result == \"user\"",
      file: "async_greet.kei",
      line: 5,
      col: 11,
    });
  }
  return kei$result;
}
//# sourceMappingURL=async_greet.ts.map
