// Generated by kei_emit from greeter_hello.kei.
// Do not edit; regenerate with `kei build`.

import * as greeter from "greeter";

export function hello(name: string): string {
  return greeter.greet(name);
}
//# sourceMappingURL=greeter_hello.ts.map
