// Generated by kei_emit from http_stock.kei.
// Do not edit; regenerate with `kei build`.

import { KeiContractViolation, keiMapGet } from "@kei/runtime";
import { HttpRequest, HttpResponse, noHeaders } from "../app/http_model";

export type StockDeps = {
  readonly inventory: ReadonlyMap<string, number>;
};

export function StockDeps(fields: StockDeps): StockDeps {
  return fields;
}

export function stockResponse(qty: number): HttpResponse {
  return HttpResponse({ status: 200, headers: noHeaders(), bodyText: "{\"qty\":" + String(qty) + "}" });
}

export function notFoundResponse(): HttpResponse {
  return HttpResponse({ status: 404, headers: noHeaders(), bodyText: "{\"error\":\"not found\"}" });
}

/**
 * requires sku.length > 0
 */
export function lookupStock(deps: StockDeps, sku: string): HttpResponse {
  if (!(sku.length > 0)) {
    throw new KeiContractViolation({
      clause: "requires",
      func: "lookupStock",
      condition: "sku.length > 0",
      file: "http_stock.kei",
      line: 18,
      col: 12,
    });
  }
  return (() => {
    const kei$m0 = keiMapGet(deps.inventory, sku);
    if (kei$m0.ok) {
      const qty = kei$m0.value;
      return stockResponse(qty);
    }
    if (!kei$m0.ok) {
      return notFoundResponse();
    }
    throw new Error("non-exhaustive match");
  })();
}

export function handleStock(deps: StockDeps, req: HttpRequest): HttpResponse {
  return (() => {
    const kei$m1 = keiMapGet(req.pathParams, "sku");
    if (kei$m1.ok) {
      const sku = kei$m1.value;
      return lookupStock(deps, sku);
    }
    if (!kei$m1.ok) {
      return notFoundResponse();
    }
    throw new Error("non-exhaustive match");
  })();
}
//# sourceMappingURL=http_stock.ts.map
