// Generated by kei_emit from http_model.kei.
// Do not edit; regenerate with `kei build`.

import { Option } from "@kei/runtime";

export type HttpRequest = {
  readonly method: string;
  readonly path: string;
  readonly headers: ReadonlyMap<string, string>;
  readonly queryParams: ReadonlyMap<string, string>;
  readonly bodyText: Option<string>;
};

export function HttpRequest(fields: HttpRequest): HttpRequest {
  return fields;
}

export type HttpResponse = {
  readonly status: number;
  readonly headers: ReadonlyMap<string, string>;
  readonly bodyText: string;
};

export function HttpResponse(fields: HttpResponse): HttpResponse {
  return fields;
}

export function noHeaders(): ReadonlyMap<string, string> {
  return new Map();
}
//# sourceMappingURL=http_model.ts.map
