// Generated by kei_emit from http_ensures_probe.kei.
// Do not edit; regenerate with `kei build`.

import { KeiContractViolation } from "@kei/runtime";
import { HttpRequest, HttpResponse, noHeaders } from "../app/http_model";

/**
 * ensures result.status == 200
 */
export function brokenHandler(req: HttpRequest): HttpResponse {
  const kei$result = ((): HttpResponse => {
    return HttpResponse({ status: 500, headers: noHeaders(), bodyText: "{}" });
  })();
  if (!(kei$result.status === 200)) {
    throw new KeiContractViolation({
      clause: "ensures",
      func: "brokenHandler",
      condition: "result.status == 200",
      file: "http_ensures_probe.kei",
      line: 6,
      col: 11,
    });
  }
  return kei$result;
}
//# sourceMappingURL=http_ensures_probe.ts.map
