// Generated by kei_emit from http_users.kei.
// Do not edit; regenerate with `kei build`.

import { KeiContractViolation } from "@kei/runtime";
import { HttpRequest, HttpResponse, noHeaders } from "../app/http_model";
import * as parseApp from "parse-app";

export type UserRequest = {
  readonly name: string;
};

export function UserRequest(fields: UserRequest): UserRequest {
  return fields;
}

export function acceptedResponse(): HttpResponse {
  return HttpResponse({ status: 202, headers: noHeaders(), bodyText: "{\"status\":\"accepted\"}" });
}

export function badRequestResponse(): HttpResponse {
  return HttpResponse({ status: 400, headers: noHeaders(), bodyText: "{\"error\":\"invalid request\"}" });
}

/**
 * requires user.name.length > 0
 */
export function buildCreatedResponse(user: UserRequest): HttpResponse {
  if (!(user.name.length > 0)) {
    throw new KeiContractViolation({
      clause: "requires",
      func: "buildCreatedResponse",
      condition: "user.name.length > 0",
      file: "http_users.kei",
      line: 22,
      col: 12,
    });
  }
  return acceptedResponse();
}

/**
 * uses Async
 */
export async function handleCreateUser(req: HttpRequest): Promise<HttpResponse> {
  return (() => {
    const kei$m0 = req.bodyText;
    if (kei$m0.ok) {
      const text = kei$m0.value;
      return (() => {
        const kei$m1 = parseApp.parseUserRequest(text);
        if (kei$m1.ok) {
          const user = kei$m1.value;
          return buildCreatedResponse(user);
        }
        if (!kei$m1.ok) {
          return badRequestResponse();
        }
        throw new Error("non-exhaustive match");
      })();
    }
    if (!kei$m0.ok) {
      return badRequestResponse();
    }
    throw new Error("non-exhaustive match");
  })();
}
//# sourceMappingURL=http_users.ts.map
