// Generated by kei_emit from http_health.kei.
// Do not edit; regenerate with `kei build`.

import { KeiContractViolation } from "@kei/runtime";
import { HttpRequest, HttpResponse, noHeaders } from "../app/http_model";

export function healthBody(): string {
  return "{\"status\":\"ok\"}";
}

/**
 * ensures result.status == 200
 */
export function handleHealth(req: HttpRequest): HttpResponse {
  const kei$result = ((): HttpResponse => {
    return HttpResponse({ status: 200, headers: noHeaders(), bodyText: healthBody() });
  })();
  if (!(kei$result.status === 200)) {
    throw new KeiContractViolation({
      clause: "ensures",
      func: "handleHealth",
      condition: "result.status == 200",
      file: "http_health.kei",
      line: 10,
      col: 11,
    });
  }
  return kei$result;
}
//# sourceMappingURL=http_health.ts.map
